//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pymes.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditoriasABM
    {
        public int IdAuditoriaABM { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Tabla { get; set; }
        public Nullable<int> IdRegistro { get; set; }
        public string AccionABM { get; set; }
        public string Observaciones { get; set; }
        public string IdSession { get; set; }
    }
}
