//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pymes.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contacto
    {
        public int IdContacto { get; set; }
        public string Nombre { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public Nullable<int> Telefono { get; set; }
        public Nullable<int> IdCategoria { get; set; }
    }
}
