//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pymes.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int IdMenu { get; set; }
        public string Nombre { get; set; }
        public string Url { get; set; }
        public Nullable<int> IdMenuPadre { get; set; }
        public Nullable<byte> Orden { get; set; }
        public Nullable<int> IdPermiso { get; set; }
    }
}
