//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pymes.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class VentasDetalle
    {
        public int IdVentaDetalle { get; set; }
        public int IdVenta { get; set; }
        public Nullable<int> IdArticulo { get; set; }
        public string Cantidad { get; set; }
        public Nullable<decimal> Precio { get; set; }
    }
}
