//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pymes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public int IdCliente { get; set; }
        public string Nombre { get; set; }
        public Nullable<long> Cuit { get; set; }
        public string IdTipoDocumento { get; set; }
        public Nullable<long> NumeroDocumento { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string IdSexo { get; set; }
        public string IdEstadoCivil { get; set; }
        public string Calle { get; set; }
        public Nullable<int> NumeroCalle { get; set; }
        public string Localidad { get; set; }
        public Nullable<int> IdDepartamento { get; set; }
        public Nullable<int> IdProvincia { get; set; }
        public Nullable<int> IdPais { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<System.DateTime> FechaEgreso { get; set; }
        public Nullable<bool> TieneTrabajo { get; set; }
        public Nullable<bool> TieneAuto { get; set; }
        public Nullable<bool> TieneCasa { get; set; }
        public Nullable<decimal> CreditoMaximo { get; set; }
        public string Mail { get; set; }
        public string Clave { get; set; }
        public Nullable<int> IdUsuario { get; set; }
    }
}
